apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.27"

vpc:
  id: "vpc-0c3e4aa6bb6bbeae5"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a: { id: subnet-099148d4c48a5dae5 }
      us-east-1b: { id: subnet-03c61062ee2343c5c }
      us-east-1c: { id: subnet-06452a382f1b78aeb }

managedNodeGroups:
  - name: ng-db
#    ami: "ami-051f7e7f6c2f40dc1"
    instanceType: t2.micro
    labels: { role: builders }
    minSize: 2
    maxSize: 2
    ssh: 
      allow: true
      publicKeyName: devops
    tags:
      Name: ng-db
