apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: fargate-cluster
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
